- hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Install collection
      shell: "pip install proxmoxer"
    - name: Cloning virtual machine ubuntu-20.04-server 
      proxmox_kvm:
        api_host : "192.168.68.57"
        api_user : root@pam
        api_token_id: 'root-ansible'
        api_token_secret: '0d164179-51fb-437f-9dc8-34b94b067c96'
        name : "ubuntu-20.04-server-test"
        node : "c1"
        clone: "ubuntu-20.04-server"
        timeout: 300