- hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Install collection
      shell: "pip install proxmoxer"
      delegate_to: localhost

    - name: Cloning virtual machine ubuntu-20.04-server 
      community.general.proxmox:
        api_host : 192.168.68.57
        api_user : root@pam
        api_token_id: 'root-ansible'
        api_token_secret: '0d164179-51fb-437f-9dc8-34b94b067c96'
        vmid: 1010
        node: promox
        clone: 8001 # 'ubuntu-20.04-server'
        hostname: test.com
        description: created with ansible
        timeout: 300
      delegate_to: localhost