- hosts: all
  gather_facts: false
  tasks:
    - name: Install collection
      shell: "pip install proxmoxer" 

    - name: Create new container with minimal options
      community.general.proxmox:
        api_host: 192.168.68.57
        api_user: 'root@pam'
        api_token_id: 'root-ansible'
        api_token_secret: '0d164179-51fb-437f-9dc8-34b94b067c96'
        vmid: 100
        node: c1
        hostname: nuevo.com
        ostemplate: 'local:vztmpl/ubuntu-14.04-x86_64.tar.gz'
        description: created with ansible
      delegate_to: localhost